config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => "localhost:3000"

  root 'users#show'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :lists
  end
  
  resources :lists, only: [:show] do
    resources :movies
  end
  resources :movie_lists
  resources :movies

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [ :new, :create, :edit, :update]
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :movie_lists
  has_many :movies, through: :movie_lists
  default_scope { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 149 },
                    uniqueness: {
                      scope: :user,
                      case_sensetive: false}
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = current_user.lists.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = current_user.lists.build if logged_in?
    respond_to :js
  end

  def create
    @list = current_user.lists.build(list_params)
      respond_to do |format|
        format.js {
          unless @list.save
            flash.now[:danger] = @list.errors.full_messages.to_sentence
            render :new
          end
        }
      end
    # debugger
  end

  def edit
    @list = current_user.lists.find(params[:id])
  end

  def update
    @list = current_user.lists.find(params[:id])
    @list.update(list_params)
      respond_to do |format|
        format.js {
          unless @list.valid?
            flash[:danger] = @list.errors.full_messages.to_sentence
            render :edit
          end
        }
      end
  end

  def destroy
    @list = current_user.lists.find(params[:id])
    flash[:danger] = 'Something went wrong' unless @list.destroy
  end

  private

    def list_params
      params.require(:list).permit(:title, :is_private)
    end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<div class="col-auto">
</div>
<div class="col-auto d-flex p-0">
  <div id="flash-message" class=" d-inline-block px-3 my-auto" style="display:none;"></div>

  <%=image_tag("cross.svg",
      class: "d-inline-block my-auto px-3 btn",
      id: "cancel-list-create",
      height: "24px") %>


  <%= form_for [current_user, @list],
      remote: true,
      class: "d-inline-block" do |f| %>
    <%= f.text_field :title,
        placeholder: "List title...",
        autofocus: true,
        class:"list-input-title" %>
    <%= f.submit class:"list-input-button tem-btn btn"%>
  <% end %>
</div>

app/views/lists/_list.html.erb
<div class="grid-item mx-2" id="list-<%= list.id %>">
  <div>
    <div class="list-buttons-wrap">
      <div class="list-buttons d-flex">

        <%= link_to [current_user, list],
            class: "d-inline-flex list-button tem-btn btn text-danger",
            method: :delete,
            remote: true do %>
          <div class="m-auto">Delete</div>
        <% end %>

        <%= link_to [:edit, current_user, list],
            class: "d-inline-flex list-button tem-btn btn",
            remote: true do %>
          <div class="m-auto">Rename</div>
        <% end %>

        <%= link_to list,
            class: "d-inline-flex list-icon tem-btn",
            target: "_blank" do %>
         <%=image_tag("share.svg", class: "m-auto btn", height: "24px") %>
        <% end %>

        <div class="d-inline-flex list-icon tem-btn ">
          <%=image_tag("cross.svg", class: "m-auto btn", height: "24px") %>
        </div>

      </div>
    </div>

    <div class="list-head-wrap border-bottom" style="overflow: hidden">
      <div class="list-head" style="position: relative">
        <div class="list-title" id="<%= list.id %>">
          <%= list.title %>
        </div>
        <div class="text-right add-movie-button">
          <%= link_to "Add Movie", new_movie_list_path(list_id: list.id),
              remote: true,
              class: "tem-btn btn" %>
        </div>
      </div>
    </div>

    <div id="add-movie-input-<%= list.id %>" class="d-flex"></div>

    <div id="movies-holder" class="movies-list border-bottom">
      <%if list.movie_lists.any? %>

        <% list.movie_lists.each do |movie_list| %>
          <% unless movie_list.seen %>
            <%= render movie_list %>
          <% end %>
        <% end %>

      <% end %>

      <div id="seen">
        <%if list.movie_lists.any? %>
            <% list.movie_lists.each do |movie_list| %>
              <% if movie_list.seen %>
                <%= render movie_list %>
              <% end %>
            <% end %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/lists/create.js.erb

$("#top-menu").html("<%= j render partial: 'layouts/top_menu' %>");
$(".lists").prepend("<%= j render @list %>");
new_list = $("#list-<%= j @list.id.to_s %>");
$(".grid").masonry()
  .prepend( new_list )
  .masonry( 'prepended', new_list )
  .masonry();

app/views/lists/destroy.js.erb
var error = "<%= j flash.now[:danger] %>";

if (error) {
  $.FlashMessage("danger", error);

} else {
  list = $("#list-<%= j @list.id.to_s %>");
  $(".grid").masonry()
    .masonry( 'remove', list )
    // layout
    .masonry();

  list.remove();
}

app/views/lists/edit.js.erb
var error = "<%= j flash.now[:danger] %>";

if (error) {
  $.FlashMessage("danger", error);
  <% flash.discard %>
} else {
  $("#top-menu").html("<%= j render partial: 'lists/form', locals: {new_list: @list} %>");
  $(".list-input-title").focus();
}

app/views/lists/index.html.erb
<% @lists.each do |l| %>
  <div>
    <%= link_to l.title, user_list_path(current_user, l) %>
    <%= link_to 'delete', user_list_path(current_user, l), method: :delete %>
    <%= link_to 'edit', edit_user_list_path(current_user, l) %>
  </div>
<% end %>

app/views/lists/new.js.erb
var error = "<%= j flash.now[:danger] %>";

if (error) {
  $.FlashMessage("danger", error);
  <% flash.discard %>
} else {
  $("#top-menu").html("<%= j render partial: 'lists/form', locals: {new_list: @list} %>");
  $(".list-input-title").focus();
}

app/views/lists/show.html.erb
<div class="container my-2">
  <div class="border-bottom mx-auto"
    style="font-weight: 900;font-size: 4em;">
    <%= @list.title %>
  </div>

  <% if @list.movie_lists.any? %>
  <% @list.movie_lists.each do |movie_list| %>
  <div class="py-3 movie-list-movie-title"
    style="font-size: 2em;">
    <%= movie_list.movie.title %>
  </div>
  <% end %>
  <% end %>

</div>

app/views/lists/update.js.erb
$("#list-<%= j @list.id.to_s %> .list-title").html("<%= j @list.title %>")
$("#top-menu").html("<%= j render partial: 'layouts/top_menu' %>");