config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => "localhost:3000"

  root 'users#show'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :lists
  end
  
  resources :lists, only: [:show] do
    resources :movies
  end
  resources :movie_lists
  resources :movies

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [ :new, :create, :edit, :update]
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  respond_to :js
  #
  # def index
  #   @movies = Movie.all
  # end

  def show
    respond_to do |format|
      format.js{
        @movie = Movie.find(params[:id])
      }
    end
  end

  def create
    respond_to do |format|
      format.js{
        @movie = Movie.create_with(movie_params).find_or_create_by(tmdb_id: movie_params[:tmdb_id])
      }
    end
  end

  private
    def movie_params
      params.require(:movie).permit(:title,
                                    :tmdb_id,
                                    :show,
                                    :poster_path)
    end
end

app/views/movies/_form.html.erb
<!-- <% form_for @movie, hidden:true do |f| %>
  <% f.text_field :title, id: "movie-title-field" %>
  <% f.check_box :show, id: "show-check" %>
  <% f.text_field :link, id: "movie-id" %>
  <%= f.submit 'Add' %>
<% end %> -->

app/views/movies/_movie.html.erb

  <%=image_tag("cross.svg",
      class: "m-auto btn",
      id: "close-movie-details",
      style: "height:42px; top: 5%;position: absolute;left: 90%;",
      height: "24px") %>


<div id="movie-details" class="movie-grid d-flex" style="width: 50vw;">
  <div id="poster-holder" class="grid-item--movie d-inline">
    <img src="no-poster.svg" alt="no-poster"
         style="width: inherit"
         class="img-responsive">
  </div>

  <div id="movie-info" class="grid-item--movie p-3 d-inline">
    <h1> <%= movie.title %> </h1>
  </div>
</div>

app/views/movies/_movie_details.html.erb
<!-- <div class="modal-box container" id="movie-details-modal" style="display: none">
  <div class="d-inline-block" id="movie-poster" style="height: 100%">
    <div class="image-placeholder">
      <img src="no-poster.svg" alt="no-poster">
    </div>
  </div>
  <div class="d-inline-block" id="info">
    <div class="" id="modal-title">
      <%= movie.title %>
    </div>
    <%= link_to "Add", movies_path(movie: movie_params, list_id: params[:list_id]),
                       remote: true,
                       method: :post %>
  </div>
</div> -->

app/views/movies/create.js.erb
$.ajax({
  url: "/movie_lists",
  type: "POST",
  headers: { 'X-CSRF-Token': Rails.csrfToken() },
  data: {movie_id: <%= j @movie.id.to_s %>,
         id: list_id_param}
  });

app/views/movies/index.html.erb
<%= link_to "New Movie", new_movie_path %>
<% @movies.each do |m| %>
  <div>
    <%= link_to m.title, movie_path(m), remote: true %>
  </div>

<% end %>

<div id="movie-details-modal-holder"></div>

app/views/movies/new.html.erb
<!-- <%= form_for @movie, hidden:true do |f| %>
  <% f.text_field :title, id: "movie-title-field" %>
  <% f.check_box :show, id: "show-check" %>
  <% f.text_field :link, id: "movie-id" %>
  <%= f.submit 'Add' %>
<% end %> -->

app/views/movies/show.js.erb
var poster_path = "<%= j @movie.poster_path %>"
var poster_780 = "https://image.tmdb.org/t/p/w780" + poster_path;

$("#movie-details-holder")
  .html("<%= j render @movie %>");

open_modal = $("#movie-details-holder");

open_modal.show(function() {

    open_modal.animate({
      opacity: 1
    }, 100, function() {
      $("body").css({
        overflow: "hidden"
      });
    });

    $("#movie-details").animate({
      top: "50%"
    }, 300, function() {
      open_modal.css({
        overflow: "auto"
      });
      if (poster_path) {
        $("#poster-holder")
        .prepend($('<img>',{id: "poster", src: poster_780, class:"img-responsive"}));
      }

      $('.movie-grid').masonry();
    });
});